package net.fabricmc.tinyremapper.api;

import org.objectweb.asm.Opcodes;

public interface TrMethod extends TrMember {
	/**
	 * A bridge method, generated by the compiler.
	 */
	default boolean isBridge() {
		return getType().equals(MemberType.METHOD) && (getAccess() & Opcodes.ACC_BRIDGE) != 0;
	}

	/**
	 * Declared native; implemented in a language other than the Java programming language.
	 */
	default boolean isNative() {
		return getType().equals(MemberType.METHOD) && (getAccess() & Opcodes.ACC_NATIVE) != 0;
	}

	/**
	 * Declared abstract; no implementation is provided.
	 */
	default boolean isAbstract() {
		return getType().equals(MemberType.METHOD) && (getAccess() & Opcodes.ACC_ABSTRACT) != 0;
	}

	/**
	 * Non-static and non-private method.
	 */
	default boolean isVirtual() {
		return getType().equals(MemberType.METHOD) && (getAccess() & (Opcodes.ACC_STATIC | Opcodes.ACC_PRIVATE)) == 0;
	}
}
